[package]
name = "rust_tif"
version = "0.1.0"
edition = "2021"

[lib]
name = "rust_tif"
path = "src/rust_lib.rs"

[dependencies]
gdal = { version = "0.15.0", features = ["array"] }
ndarray = { version = "0.15.6" }
